### PR TITLE
perf: Use string interning for HTTP methods & popular headers

### PR DESCRIPTION
**Pull request by Stranger6667**
Hey! Thank you for working on this!

This PR shows possible performance improvements via string interning. I guess it might be a bit slower for one-off use cases (but I assume they are pretty rare) due to the cell overhead, but shows a consistent improvement in the benchmark locally - 1.44 µs (main) vs. 1.26 µs (this branch) which is >10%. 

Let me know what you think! The PR is mostly to start a discussion about whether it is the right direction or not.

P.S. header names are chosen based on the benchmark and are highly arbitrary, but I guess that interning should be done for the most popular ones.

### CODE REVIEW

**Comment by adriangb** [comment]
Hey thanks for the PR!

A couple thoughts:
1) This is very easy to understand, I have no problems with it from that perspective.
2) The benchmarks I put in here aren’t great, I’m not sure that they’re representative of real world usage, they were mostly to ballpark.
3) How does this interplay with header casing? There’s no header normalization going on here so in theory we could get `authorization`. I assume most browsers do use title case though so this is probably still going to hit the fast path on average. On the other hand the ASGI spec requires all incoming headers to be lowercases by the server. So if we know this is going to be used for an ASGI served, it would be a huge win to lowercase them in Rust and possibly get even more hits on interned strings. Interestingly this would make this library look worse on these sorts of microbenchmarks even if it performed much better as part of an ASGI server.

**Comment by adriangb** [comment]
As a side note, I think you’re much more experienced with Rust than I am, any interest in building a full ASGI server so that we can take advantage of things like knowing we’ll need to lowercase headers, that the names actually need to be bytes not a string, etc?

**Comment by Stranger6667** [comment]
Thank you so much for your feedback!

I think that having some more real-world data will definitely help to define the most popular header values and use them to maximize performance for such cases. 

Great catch on casing! I think that the parsing process could be specialized for cases such as ASGI. I'd assume that having a relatively small number of arms in the header name match statement won't hurt performance much (i.e. include lower-cased names there as well), but it could look something like this to minimize the match size:

```rust
trait HeaderFlavor {
    fn intern(py: Python, value: &str) -> Py<PyString>;
}

struct GenericHeader;

impl HeaderFlavor for GenericHeader {
    fn intern(py: Python, value: &str) -> Py<PyString> {
        // TODO: Maybe some nice macro to generate this match?
        match value {
            "Host" => intern!(py, "Host"),
            "Connection" => intern!(py, "Connection"),
            "Cache-Control" => {
                intern!(py, "Cache-Control")
            }
            "Accept" => intern!(py, "Accept"),
            "User-Agent" => intern!(py, "User-Agent"),
            "Accept-Encoding" => {
                intern!(py, "Accept-Encoding")
            }
            "Accept-Language" => {
                intern!(py, "Accept-Language")
            }
            "Accept-Charset" => {
                intern!(py, "Accept-Charset")
            }
            "Cookie" => intern!(py, "Cookie"),
            name => PyString::new(py, name),
        }
        .into()
    }
}

struct AsgiHeader;

impl HeaderFlavor for AsgiHeader {
    fn intern(py: Python, value: &str) -> Py<PyString> {
        match value {
            "host" => intern!(py, "host"),
            "connection" => intern!(py, "connection"),
            "cache-control" => {
                intern!(py, "cache-control")
            }
            "accept" => intern!(py, "accept"),
            "user-agent" => intern!(py, "user-agent"),
            "accept-encoding" => {
                intern!(py, "accept-encoding")
            }
            "accept-language" => {
                intern!(py, "accept-language")
            }
            "accept-charset" => {
                intern!(py, "accept-charset")
            }
            "cookie" => intern!(py, "cookie"),
            name => PyString::new(py, name),
        }
        .into()
    }
}

#[pymethods]
impl RequestParser {
    #[new]
    fn py_new() -> Self {
        RequestParser {}
    }
    fn parse(&mut self, buff: &PyBytes, py: Python) -> PyResult<Option<ParsedRequest>> {
        self.parse_impl::<GenericHeader>(buff, py)
    }
    fn parse_asgi(&mut self, buff: &PyBytes, py: Python) -> PyResult<Option<ParsedRequest>> {
        self.parse_impl::<AsgiHeader>(buff, py)
    }
}

impl RequestParser {
    fn parse_impl<F: HeaderFlavor>(
        &mut self,
        buff: &PyBytes,
        py: Python,
    ) -> PyResult<Option<ParsedRequest>> {
        let mut headers = [httparse::EMPTY_HEADER; 256];
        let mut request = httparse::Request::new(&mut headers);
        let maybe_status = request.parse(buff.as_bytes());
        match maybe_status {
            Ok(status) => Ok({
                match status.is_complete() {
                    true => {
                        let header_list: Py<PyList> = PyList::new(
                            py,
                            request.headers.into_iter().map(|h| {
                                Py::new(
                                    py,
                                    Header {
                                        name: F::intern(py, h.name),
                                        value: PyBytes::new(py, h.value).into(),
                                    },
                                )
                                .unwrap()
                            }),
                        )
                        .into();
                        let method = match request.method.unwrap() {
                            "GET" => intern!(py, "GET"),
                            "POST" => intern!(py, "POST"),
                            "PUT" => intern!(py, "PUT"),
                            "PATCH" => intern!(py, "PATCH"),
                            "DELETE" => intern!(py, "DELETE"),
                            "HEAD" => intern!(py, "HEAD"),
                            "OPTIONS" => intern!(py, "OPTIONS"),
                            "TRACE" => intern!(py, "TRACE"),
                            "CONNECT" => intern!(py, "CONNECT"),
                            other => PyString::new(py, other),
                        }
                        .into();

                        Some(ParsedRequest {
                            method,
                            path: PyString::new(py, request.path.unwrap()).into(),
                            version: request.version.unwrap(),
                            headers: header_list,
                            body_start_offset: status.unwrap(),
                        })
                    }
                    false => None,
                }
            }),
            Err(parse_error) => match parse_error {
                httparse::Error::HeaderName => Err(InvalidHeaderName::new_err(())),
                httparse::Error::HeaderValue => Err(InvalidHeaderValue::new_err(())),
                httparse::Error::NewLine => Err(InvalidByteInNewLine::new_err(())),
                httparse::Error::Token => Err(InvalidToken::new_err(())),
                httparse::Error::TooManyHeaders => Err(TooManyHeaders::new_err(())),
                httparse::Error::Version => Err(InvalidHTTPVersion::new_err(())),
                _ => panic!(),
            },
        }
    }
}
```

Re: building an ASGI server. I'd be happy to participate, though I am not sure about my bandwidth in the upcoming weeks as I start a new job next Monday. However, feel free to tag me in any kind of discussions / PRs about this matter :)

**Comment by Stranger6667** [comment]
P.S. I am not much aware of the whole ASGI workflow, but I am definitely tend to move more stuff to the Rust side if it makes sense :)

**Comment by adriangb** [comment]
Let’s merge this for now since it’s a cool idea and is an improvement for the general case. I think an ASGI server would be another package. Thanks for the contribution!

**Pull request merged**
